#!/usr/bin/bash

# Monitor configuration
INTERNAL_MONITOR="eDP"
EXTERNAL_MONITOR="HDMI-0"

# Check if the first argument is 0
if [[ "$1" = 0 ]]; then
  # Check if the external monitor is connected
  if xrandr -q | grep -q "${EXTERNAL_MONITOR} connected"; then
    # Configure BSPWM monitors
    bspc monitor "$EXTERNAL_MONITOR" -d I II III IV V
    bspc monitor "$INTERNAL_MONITOR" -d VI VII VIII IX X
    bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
    
    # Uncomment the following line to set up monitor positioning with xrandr
    # xrandr --output eDP --auto --output HDMI-0 --auto --right-of eDP
  else
    # Configure BSPWM with a single monitor
    bspc monitor -d I II III IV V VI VII VIII IX X
  fi
fi

# BSPWM configuration
bspc config border_width         1
bspc config window_gap           1
bspc config split_ratio          0.50
bspc config single_monocle       false
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_modifier     mod4
bspc config pointer_action1      move
bspc config pointer_action2      resize_side
bspc config pointer_action3      resize_corner
bspc config remove_disabled_monitors   true
bspc config merge_overlapping_monitors true
bspc config focused_border_color       "#16a085" # "#B4A1DB"
bspc config normal_border_color        "#D8D8D8" # "#9EE9EA"
bspc config active_border_color        "#E49186"

# Autostart applications

# Start sxhkd (X hotkey daemon)
sxhkd -c ~/.config/sxhkd/sxhkdrc &

# Start the main polybar
polybar -c ~/.config/polybar/config.ini main &

# Start the secondary polybar if the external monitor is connected
if xrandr -q | grep -q "${EXTERNAL_MONITOR} connected"; then
  polybar -c ~/.config/polybar/config.ini secondary &
fi

# Start picom (compositor)
picom --config ~/.config/picom/picom.conf --experimental-backends &

# Set wallpaper using feh
feh --bg-fill feh --bg-fill /usr/share/wallpapers/Gorilla_Yaru-Teal.jpg &  #/usr/share/wallpapers/wallhaven-m3zjx1_1920x1080.png &

# Set keyboard layout (US and Greek) with option to toggle using Shift+Caps Lock
setxkbmap -layout us,gr -variant , -option grp:shift_caps_toggle &

# Start xautolock to lock and suspend system for inactivity
xautolock -time 15 -locker 'systemctl suspend' -notify 600 -notifier '~/.local/bin/betterlockscreen -l' &

# Start dunst (notification daemon)
/usr/bin/dunst &

# Enable numlock on startup
numlockx on &

# Other commands

# Set cursor to left_ptr
xsetroot -cursor_name left_ptr &
