#!/bin/sh

# Single monitor
# bspc monitor -d I II III IV V VI VII VIII IX X

INTERNAL_MONITOR="eDP"
EXTERNAL_MONITOR="HDMI-0"
if [[ "$1" = 0 ]]; then
 if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
  bspc monitor "$EXTERNAL_MONITOR" -d 1 2 3 4 5
  bspc monitor "$INTERNAL_MONITOR" -d 6 7 8 9 10
  bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
  xrandr --output eDP  --auto --output HDMI-0 --auto --right-of eDP
  #xrandr --output eDP  --auto --output HDMI-0 --auto --left-of eDP
 else
  bspc monitor -d I II III IV V VI VII VIII IX X
 fi
fi
                       
# BSPWM configuration
bspc config border_width         2
bspc config window_gap           4
#bspc config top_padding          0
# When polybar is at the bottom dont use bottom padding. Same thing for top.
#bspc config bottom_padding       48
#bspc config left_padding         0
#bspc config right_padding        0
bspc config split_ratio          0.50
bspc config single_monocle       false
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

# Border
bspc config focused_border_color        "#B4A1DB"
bspc config normal_border_color         "#9EE9EA"
bspc config active_border_color         "#E49186"

########## Autostart ##########
# sxhkd
sxhkd -c ~/.config/bspwm/sxhkd/sxhkdrc &
# Bar
#killall -q polybar 
polybar -c ~/.config/bspwm/polybar/manhattan/config.ini main &
if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
  polybar -c ~/.config/bspwm/polybar/manhattan/config.ini secondary &
fi
# Picom
picom --config ~/.config/bspwm/picom.conf &
# Wallpaper
#feh --bg-fill /usr/share/wallpapers/wallhaven-v9py65_1280x720.png &
feh --bg-fill /usr/share/wallpapers/wallhaven-g7lyd7_1280x720.png &
# Keyboard layout + greek
setxkbmap -layout us,gr -variant , -option grp:shift_caps_toggle &
#setxkbmap -model pc104 -layout us,gr -variant , -option grp:shift_caps_toggle &
# Power management
xfce4-power-manager &

# Set display from arandr saved script
#sh ~/.screenlayout/monitor.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Network Applet
nm-applet --indicator &
# Numlock on
numlockx on &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

